# Generated by Django 3.0.6 on 2020-05-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='board',
            fields=[
                ('board_ID', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('board_name', models.CharField(max_length=20)),
                ('board_desc', models.TextField(max_length=1000)),
                ('board_picture', models.ImageField(upload_to='board')),
            ],
        ),
    ]
