# Generated by Django 3.0.6 on 2020-05-25 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('Post_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Post_Text', models.CharField(max_length=5000)),
                ('Post_IP', models.CharField(max_length=20)),
                ('Post_Photo', models.ImageField(upload_to='post')),
                ('Post_Board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.board')),
            ],
        ),
    ]
