# Generated by Django 3.0.6 on 2020-05-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Post_Text',
            field=models.TextField(max_length=5000),
        ),
    ]
